name: CI

  on: [push, pull_request]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
      - run: npx eslint .
  
- name: Send coverage to CodeClimate
    run: |
      npm test -- --coverage
      ./cc-test-reporter after-build --exit-code $CODE
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPO_TOKEN }}